version: "3.9"

services:
  db:
    image: postgres:15
    restart: always
    env_file: .env
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - db_data:/var/lib/postgresql/data

  web:
    build: .
    restart: always
    env_file: .env
    depends_on:
      - db
    ports:
      - "5000:5000"
    volumes:
      - .:/app

  nginx:
    image: nginx:alpine
    container_name: crm_nginx
    restart: always
    ports:
      - "8080:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - web
      
volumes:
  db_data: